# Hello World Numpy!
https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import numpy as np

## Simple Vector

In [2]:
a = np.array([1, 2, 3])
print("a", a)
print("type", type(a))
print("a[0]", a[0])

a [1 2 3]
type <class 'numpy.ndarray'>
a[0] 1


## Simple Matrix and indexing

In [3]:
a=np.array([[1, 2, 3] ,[4, 5, 6]])
print("a", a)
print("a[0,1]", a[0,1])
print("a[0][1]", a[0][1])


a [[1 2 3]
 [4 5 6]]
a[0,1] 2
a[0][1] 2


## Matrix properties

In [4]:
a = np.arange(15).reshape(3, 5)
print("a.shape", a.shape)
print("a.ndim", a.ndim)
print("a.dtype", a.dtype)
print("a.dtype.name", a.dtype.name)
print("a.itemsize", a.itemsize)
print("a.size", a.size)
print("a", a)

a.shape (3, 5)
a.ndim 2
a.dtype int32
a.dtype.name int32
a.itemsize 4
a.size 15
a [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Special matrices

In [5]:
a=np.empty((3, 4))
print("a", a)
b=np.zeros((3, 4))
print("b", b)
c=np.ones((3, 4))
print("c", c)
d=np.eye(3)
print("d", d)
e=np.random.randn(12).reshape((3,4))
print("e", e)

a [[1.38043519e-311 2.81617418e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.31370903e-076 4.97285880e-091 1.27964679e+161]
 [1.26934732e-076 2.67837657e-032 6.48224659e+170 4.93432906e+257]]
b [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
c [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
e [[-0.54279983 -1.28645248 -0.26178073 -0.34603694]
 [ 0.67944978 -0.01075111  0.20997294 -0.35651164]
 [-0.7894087   0.61942488 -0.29142598 -1.25555245]]


## Simple Statistics

In [6]:
print("Max", np.max(a))
print("Min", np.min(b))
print("Mean", np.mean(c))
print("Std Dev", np.std(d))


Max 4.934329057044486e+257
Min 0.0
Mean 1.0
Std Dev 0.4714045207910317


Happy Numpy coding